[project]
name = "ollama-mark-it-to-open-webui"
version = "0.1.0"
description = "Glueware to add local document loader to Open-WebUI"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.122.0",
    "markitdown[all]>=0.1.3",
    "uvicorn>=0.38.0",
]
